src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints\DateTime;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => "Electique",
        1 => "Gaz"
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range( min = 10, max=500 )
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("`^\d{2,}$`", message="Veuillez saisir un code postal valide")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"defualt" = false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @Assert\Length(min = 5, max= 255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }


    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    public function getHeatType() :string
    {
        return self::HEAT[$this->heat];
    }
    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('price')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    //Former un tableau du heat key= value, value= key
    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php


namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use PhpParser\Node\Scalar\String_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /***
     * @var PropertyRepository
     */
    private $repository;

    /***
     * @var ObjectManager
     */
    private $objectManager;

    public function __construct(PropertyRepository $propertyRepository, EntityManagerInterface $objectManager)
    {
        $this->repository = $propertyRepository ;
        $this->objectManager = $objectManager ;
    }

    /**
     * @Route("/biens" , name="property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        //Traiter le filtre
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class,$search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
           $this->repository->findAllVisibleQuery($search),
           $request->query->getInt('page',1),
           9
       );
        return $this->Render("property/index.html.twig",
            [
                'current_menu' => 'properties',
                'properties' => $properties,
                'form' => $form->createView()
            ]);
    }

    /**
     * @Route("/biens/{slug}-{id}" , name="property.show", requirements={"slug" = "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Property $property, string $slug): Response
    {

        //Si ce n'est pas le bon slug
        if($property->getSlug() !== $slug)
        {
            $this->redirectToRoute("property.show", [
                'id' => $property->getId(),
                'slug'=> $property->getSlug()
                ],301);
        }
        return $this->render("property/show.html.twig",
        [
            "property"=> $property,
            'current_menu' => 'properties'
        ]);
    }
}

templates/property/_property.html.twig
        {% if property.filename %}
            <img class="card-img-top" src=" {{ vich_uploader_asset(property,'imageFile') }}" alt="card-img-top" style="height: 280px; width: 100%; display: block;">

        {% else %}
            <img class="card-img-top" src=" {{ '/images/properties/empty.jpg' }}" alt="card-img-top" style="height: 280px; width: 100%; display: block;">

        {% endif %}

            <h5 class="card-title"><a
                        href="{{ path('property.show',{id:property.id, slug: property.slug}) }}">{{ property.title }} </a>
            </h5>
            <p class="card-text">{{ property.surface }} m²</p>
            <p class="card-text">{{ property.city }}</p>
            <p class="card-text">{{ property.postalCode }}</p>
        <div class="card-footer">
            <div class="text-primary" style="font-weight: bold">{{ property.formattedPrice }} DT</div>
        </div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Tous nos biens' %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path("home") }}">Agence immobilière</a></li>
            <li class="breadcrumb-item active" aria-current="page">Acheter</li>
        </ol>
    </nav>
        <div class="container  d-flex justify-content-center">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>

    <div class="container mt-4">
        <h1>Consulter la liste de nos biens</h1>
        <div class="card-deck">
            <div class="container">
                <div class="row">
                    <div class="container">
                        <div class="row" style=" padding: 5%;">
                            {% for property in properties %}
                                <div class="col-md-4">
                                    {% include'property/_property.html.twig' %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <div class="navigation d-flex justify-content-center">
        {{ knp_pagination_render(properties) }}
    </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path("home") }}">Agence immobilière</a></li>
            <li class="breadcrumb-item"><a href="{{ path("property.index") }}">Acheter</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ property.title }}</li>
        </ol>
    </nav>
        <div class="container p-4">
            <div class="row">
                <div class="col-md-8">

                    {% if property.filename %}
                        <img src=" {{ vich_uploader_asset(property,'imageFile') }}" alt="card-img-top"
                             style="width: 100%;length: auto">

                    {% else %}
                        <img src=" {{ '/images/properties/empty.jpg' }}" alt="card-img-top"
                             style="width: 100%;length: auto">

                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold">{{ property.getFormattedPrice }}
                        DT
                    </div>

                    <div class="alert alert-dark" role="alert">
                        <h6>Pour plus d'informations veuillez nous contacter </h6>
                        <p>Tel: +216 50 254 158</p>
                        <p>email: test@test.com</p>
                    </div>

                </div>
            </div>
        </div>

    <div class="container p-4">

        <p>
            {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <table class="table table-striped">
                    <tr>
                        <td><b>Surface habitable</b></td>
                        <td>{{ property.surface }}</td>
                    </tr>
                    <tr>
                        <td><b>Pièces</b></td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td><b>Chambres</b></td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td><b>Etage</b></td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td><b>Chauffage</b></td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>


        </div>
    </div>
{% endblock %}